# Dockerfile для разработки
FROM node:20-alpine

WORKDIR /app

# Копирование package.json
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Копирование исходного кода
COPY . .

# Открытие порта
EXPOSE 3000

# Команда будет переопределена в docker-compose.dev.yml
CMD ["npm", "run", "start:dev"]

